local utils = require('utils')

utils.keymap('', '<leader><leader>F', '<Plug>(snipe-F)')
utils.keymap('', '<leader><leader>f', '<Plug>(snipe-f)')
utils.keymap('', '<leader><leader>T', '<Plug>(snipe-T)')
utils.keymap('', '<leader><leader>t', '<Plug>(snipe-t)')
utils.keymap('', '<leader><leader>w', '<Plug>(snipe-w)')
utils.keymap('', '<leader><leader>W', '<Plug>(snipe-W)')
utils.keymap('', '<leader><leader>e', '<Plug>(snipe-e)')
utils.keymap('', '<leader><leader>E', '<Plug>(snipe-E)')
utils.keymap('', '<leader><leader>b', '<Plug>(snipe-b)')
utils.keymap('', '<leader><leader>B', '<Plug>(snipe-B)')
utils.keymap('', '<leader><leader>ge', '<Plug>(snipe-ge)')
utils.keymap('', '<leader><leader>gE', '<Plug>(snipe-gE)')
utils.keymap('n', '<leader><leader>]', '<Plug>(snipe-f-xp)')
utils.keymap('n', '<leader><leader>[', '<Plug>(snipe-F-xp)')
utils.keymap('n', '<leader><leader>x', '<Plug>(snipe-f-x)')
utils.keymap('n', '<leader><leader>X', '<Plug>(snipe-F-x)')
utils.keymap('n', '<leader><leader>r', '<Plug>(snipe-f-r)')
utils.keymap('n', '<leader><leader>R', '<Plug>(snipe-F-r)')
utils.keymap('n', '<leader><leader>i', '<Plug>(snipe-f-i)')
utils.keymap('n', '<leader><leader>I', '<Plug>(snipe-F-i)')
utils.keymap('n', '<leader><leader>a', '<Plug>(snipe-f-a)')
utils.keymap('n', '<leader><leader>A', '<Plug>(snipe-F-a)')
