[theme]
name = "slick"
[theme.overrides]
idle_bg = "#2f343f"
idle_fg = "#f3f4f5"
info_bg = "#2f343f"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°F"
service = { name = "openweathermap", api_key = "", city_id = "5400075", units = "imperial" }

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°F"
service = { name = "openweathermap", api_key = "", city_id = "5400075", units = "imperial" }

[[block]]
block = "time"
format = "%I:%M %p (%Z) %a %b %d"
timezone = "US/Pacific"
interval = 60
