[theme]
name = "slick"
[theme.overrides]
idle_bg = "#2f343f"
idle_fg = "#f3f4f5"
info_bg = "#2f343f"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 70

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
upower = true
format = "{percentage}% {time}"

[[block]]
block = "time"
format = "%I:%M %p (%Z) %a %b %d"
timezone = "US/Pacific"
interval = 60
